WPML config for dt-the7 10.12.0
OnTheGoSystems/wpml-config pull request #285
Opened 2022-08-05 13:27 UTC by gerasimovdaniel

2022-08-08 11:12 UTC, strategio requested changes
Thanks @gerasimovdaniel for your contribution!

I've left a request for 2 small changes.

And I see that [our documentation](https://wpml.org/documentation/support/language-configuration-files/how-to-register-page-builder-widgets-for-translation/) should be updated accordingly (I'll take care of that).

2022-08-08 11:12 UTC, strategio commented on dt-the7/wpml-config.xml
> +        <field type="Link" editor_type="LINK" key_of="shop_button_link">url</field>
@gerasimovdaniel, we have a new way to define this data by path:

```xml
<field type="Link" editor_type="LINK">shop_button_link>url</field>
```

We are trying to move away from this legacy `key_of` attribute (bad design decision).

[See an example here](https://github.com/OnTheGoSystems/wpml-config/blob/master/elementor/wpml-config.xml#L26)

Note that for now, the path is supported only for `fields` sub-items.

2022-08-08 11:12 UTC, strategio commented on dt-the7/wpml-config.xml
> +        <field type="Link" editor_type="LINK" key_of="empty_cart_button_link">url</field>
Same as for my previous comment, could you please use the path way:

```xml
<field type="Link" editor_type="LINK">empty_cart_button_link>url</field>
```

2022-10-19 19:52 UTC, strategio commented
Hi @gerasimovdaniel!

Is that PR still valid? Do you need help to address my comments?

Thanks!

2022-10-23 10:18 UTC, gerasimovdaniel commented
Hi @strategio!

Thanks for review!
Changes have been made.

Can you recommend any tools to generate Elementor part of config? I've made my own, but this `>` in element value seems to be invalid XML syntax and turned to be encoded.

Thank you!

2022-10-23 10:19 UTC, gerasimovdaniel commented on dt-the7/wpml-config.xml
> +        <field type="Link" editor_type="LINK" key_of="empty_cart_button_link">url</field>
Done

2022-10-23 10:20 UTC, gerasimovdaniel commented on dt-the7/wpml-config.xml
> +        <field type="Link" editor_type="LINK" key_of="shop_button_link">url</field>
Done

2022-10-25 19:01 UTC, strategio commented
Thanks @gerasimovdaniel!

However, we prefer not to update existing configurations for now. The reason if that the string name signature is not exactly the same and it could cause minor issues for people using the Classic Translation Editor that has a different approach for the translation memory.

It should not be a big issue, but we prefer to stay on the safe side.

And so I've created another PR where I took your initial changes and applied my comment suggestions directly.

Could you please give a look at https://github.com/OnTheGoSystems/wpml-config/pull/299 and confirm this config is working for you?

2022-10-25 19:01 UTC, closed without merging