[Elementor] Translate "price" from Price list widget
OnTheGoSystems/wpml-config pull request #312
Opened 2023-03-01 20:13 UTC by andrescifuentesr

Making the Price field translatable for Price list widget
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6636

2023-03-02 12:04 UTC, dgwatkins commented
@andrescifuentesr I don't think we shoud make the price translatable for everyone:

- ATE doesn't know how to translate a price
- Most customers wont want to translate prices anyway.

If a certain customer needs, he can set it in his local XML.

What do you think?

2023-03-02 16:33 UTC, andrescifuentesr commented
@dgwatkins I had the same doubts about setting this field to translate or not. The initial request was done because the user was not adding just a number but also currencies and weight, ie 5€/kg.
So, if you just add a number, that would be OK as the value will be copied directly, however, if you add a currency, you may want to translate it.
Anyway, we can leave it as it is and collect more reports, if it makes sense.

2023-03-02 17:12 UTC, dgwatkins commented
Thanks @andrescifuentesr 

I will close here then and we can follow up on the ticket.

2023-03-02 17:13 UTC, dgwatkins commented
Oops, sorry @andrescifuentesr 

I realize now that this PR has more than just the price.

I think you should remove the price from this pull request and then we can merge.
Makes sense?

2023-03-02 17:15 UTC, dgwatkins requested changes

2023-03-02 17:15 UTC, dgwatkins commented on elementor/wpml-config.xml
> +                <field type="Pricing list: price">price</field>
Remove the above line @andrescifuentesr

2023-03-02 17:15 UTC, dgwatkins commented on elementor/wpml-config.xml
> +                <field type="Pricing list: link">link>url</field>
And lets add the editor_type here:
```suggestion
                <field type="Pricing list: link"editor_type="LINK">link>url</field>        
```

2023-03-02 18:55 UTC, andrescifuentesr commented
Thanks for the help, David.
I think we are good to go.

2023-03-03 09:21 UTC, dgwatkins approved these changes

2023-03-03 09:34 UTC, merged

2023-03-03 09:35 UTC, dgwatkins commented
fixed,  merged and deployed @andrescifuentesr